# Units:
#   - time: seconds
#   - distance: pixels
#   - speed: pixels/sec
#   - rotation: degrees
#   - rotation speed: degrees/sec

robot:
  type: tank1
  size: [36, 38]
  shield: 5
  max_speed: [200.0, 100.0]
  rotation_max_speed: 100.0
  turret_rotation_max_speed: 125.0
  fire_min_interval: 0.5
  bullet_speed: 300.0     
     
map:
  size: [640, 480]
